name: Maven Pipeline

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  continuous-integration:
    name: Starting integration
    runs-on: ubuntu-latest
    services:
      mysql_db:
        image: mysql
        ports: ['3306:3306']
        env:
           MYSQL_ROOT_PASSWORD: pwd123
           MYSQL_DATABASE: pediatrics
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Installing Dependencies
      run: mvn clean install
    - name: Executing Tests
      run: mvn tests

  continuous-delivery:
    name: Delivering the Application
    runs-on: ubuntu-latest
    needs: [continuous-integration]
    steps:
    - name: Building Application
      run: echo "building" 
  
  deploy:
    name: Deploying 
    runs-on: ubuntu-latest
    needs: [continuous-delivery]
    steps:
      - name: Deploying application on the server
        run: echo "Deploying ..."
